from __future__ import annotations

import numpy as np

np.set_printoptions(precision=2, suppress=True)

BASE_COLORS = ["#B0C4DE", "#B0C4DE", "#B0C4DE", "#B0C4DE", "#B0C4DE"]
BASE_ALPHAS = [0.4, 0.5, 0.6, 0.7, 0.8]

MARKER_SIZE = 40
MARKER_STYLE = "o"
MARKER_ZORDER = 5
OUTER_MARKER_COLOR = "blue"
INNER_MARKER_COLOR = "red"

SINGLE_FIGURE_SIZE = (8, 8)
SUBPLOT_WIDTH = 6

FILLED_LINEWIDTH = 1.5
HOLLOW_LINEWIDTH = 2.0

GRID_ALPHA = 0.5
GRID_LINESTYLE = "--"

XLABEL_FONTSIZE = 10
TITLE_FONTSIZE = 14
SUBTITLE_FONTSIZE = 11
METRICS_FONTSIZE = 9

METRICS_BOX_STYLE = "round"
METRICS_BOX_FACECOLOR = "white"
METRICS_BOX_ALPHA = 0.8
METRICS_TEXT_X = 0.98
METRICS_TEXT_LEFT_X = 0.16
METRICS_TEXT_Y = 0.98

DEFAULT_PADDING = 0.1
